### ISSUE TITLE
Would be possible to add commerce support?

### ISSUE THREAD

**Issue by victorvalle** [mdelapenya/lpn#11]

**Comment by mdelapenya** [comment]
Hey @victorvalle, this seems super easy to implement, as the commerce image is built on top of nightly builds, so it would be easy.

Meanwhile, you have a workaround: use `lpn` with a `nightly`, and use the `deploy` command with commerce modules.

What do you think?

**Comment by mdelapenya** [comment]
Hey @victorvalle I added this feature to the 0.5.0-snapshot 🎉 

Please check it out updating your local binary

**Comment by mdelapenya** [comment]
![image](https://media.giphy.com/media/AvMJCeu1EMmhG/giphy.gif)
