### ISSUE TITLE
EC support

### ISSUE THREAD

**Issue by victorvalle** [mdelapenya/lpn#21]
Would it be possible to add experience cloud support as for commerce?

**Comment by mdelapenya** [comment]
Hey @victorvalle I'd need the Docker Hub repository for EC, but let's talk first about it, as we have to check that EC is just a liferay instance, only, which is what `lpn` understand.

**Comment by mdelapenya** [comment]
Closing for this moment, as we do not know much about that EC project, if it has a Docker image or so
