### ISSUE TITLE
Tomcat memory not configurable

### ISSUE THREAD

**Issue by danieldefrancisco-lr** [mdelapenya/lpn#30]
Great work with this tool.

In order to be more flexible for the users, it would be nice to customize the "run" command so that it allows to set the memory configuration for the tomcat included in the liferay bundle.
Something like : "lpn run nightly --memory 4GB"

Is that possible?

Thanks!

**Comment by mdelapenya** [comment]
We would need the underlying images (nightly and release) to be edited so that they accept that configuration, so the `lpn` tool can update it

Thanks for the feedback!

**Comment by mdelapenya** [comment]
Releases in progress: https://hub.docker.com/r/mdelapenya/liferay-portal/builds/ and https://github.com/mdelapenya/docker-liferay-portal
