### ISSUE TITLE
Use mdelapenya/portal-snapshot for nightly images

### ISSUE THREAD

**Issue by mdelapenya** [mdelapenya/lpn#91]
We are going to automate a daily job for releasing portal-snapshots here: https://hub.docker.com/r/mdelapenya/portal-snapshot

The build script will be located here, and travis will execute it every day.

With this initiative, we are going to provide a nightly build for designers using LPN tool

**Comment by mdelapenya** [comment]
cc/ @susanavr @victorvalle

**Comment by susanavr** [comment]
Manu! So cool!

**Comment by mdelapenya** [comment]
The automation is in place, I need to code it in LPN and release a new version.

![image](https://media.giphy.com/media/l41m3wQ0eoWJ9tEEE/giphy.gif)

**Comment by mdelapenya** [comment]
Problems using this new version? Please remove `~/.lpn` directory and execute the CLI again.

## Linux and Mac
```shell
$ rm -fr ~/.lpn
```

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/D0WOL0ogZIoG4/giphy.gif)

**Comment by mdelapenya** [comment]
@susanavr @victorvalle are you or your teams using it?

Please feedback! 🙏 

![image](https://media.giphy.com/media/uetToBcxTS9bi/giphy.gif)

**Comment by susanavr** [comment]
Hi @mdelapenya! I'm so sorry. I would like to say yes... but right now I am not using it. I need to sync up with Analytics Cloud, so my team helped me to do all the steps... but I hope to use it again as soon as possible because I was much more easier!

**Comment by mdelapenya** [comment]
What do you need for running Analytics Cloud? a specific docker image?

**Comment by victorvalle** [comment]
I'm using the new version already. Sorry for the delay but I had no time to try. So far I'm able to download and run the official Liferay Docker images.

Thank you Manu!

I will try to play with the tool a bit more
